# Generated by Django 4.1.5 on 2023-04-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_user_newuser_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('rating', models.FloatField()),
                ('likedpercent', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('pages', models.IntegerField()),
                ('genres', models.CharField(max_length=1000)),
                ('coverImg', models.CharField(max_length=500)),
            ],
        ),
    ]
