# Generated by Django 4.1.5 on 2023-04-28 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='coverImg',
        ),
    ]
