# Generated by Django 4.1.5 on 2023-04-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0009_usertoread'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoread',
            name='bookscompleted',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
